### ISSUE TITLE
help request: After using a custom Java plugin for deployment, the error log keeps restarting the jar

### ISSUE THREAD

**Issue by adairll** [apache/apisix#10074]
### Description

Hello, I have encountered some problems and hope to receive help

Developed using github 【apisix-java-plugin-runner-main】and
Reference Blog [https://apisix.apache.org/zh/blog/2021/06/21/use-java-to-write-apache-apisix-plugins/]

apisix config.yaml
`deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_key:
      - name: admin
        key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
        role: admin
apisix:
  node_listen: 8000 # APISIX listening port

ext-plugin:
  cmd: ['java', '-jar', '/usr/local/apisix/apisix/plugins/apisix-runner-bin/apisix-java-plugin-runner.jar']`

error log
`2023-08-22 21:04:59,224 ERROR main                             - Application run failed
 java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:785)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
	at org.apache.apisix.plugin.runner.PluginRunnerApplication.main(PluginRunnerApplication.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: No such file or directory`

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by yuluo-yx** [comment]
The stack exception is: `bind(..) failed: No such file or directory`. Is your application.yml configured correctly, please refer to
```yml
server:
  port: 30001

spring:
  application:
    name: apisix-java-plugin-runner

cache.config:
  expired: ${APISIX_CONF_EXPIRE_TIME}
  capacity: 1000

socket:
  file: ${APISIX_LISTEN_ADDRESS}
```

@adairll

**Comment by Revolyssup** [comment]
@adairll Any updates here?

**Comment by dagvl** [comment]
I have what looks like the same issue, but with a go plugin instead. I've just compiled the example go plugins and added them into the kubernetes pod. 

The logs show that it starts and has gotten the path `unix:/conf/apisix-1.sock` which is expected. However, this path does not exist in my docker container / pod. 

This is using the bitnami charts and docker images because I need arm64 images. 

```
│ 2023/10/10 22:05:29 [warn] 17#17: *170 [lua] init.lua:971: respawning new runner..., context: ngx.timer
│ 2023/10/10 22:05:29 [warn] 17#17: *170 [lua] init.lua:953: 2023-10-10T22:05:29.676Z    INFO    plugin/plugin.go:73    register plugin fault-injection
│ 2023-10-10T22:05:29.676Z    INFO    plugin/plugin.go:73    register plugin limit-req
│ , context: ngx.timer
│ 2023/10/10 22:05:29 [warn] 17#17: *170 [lua] init.lua:953: 2023-10-10T22:05:29.676Z    INFO    plugin/plugin.go:73    register plugin response-rewrite
│ 2023-10-10T22:05:29.676Z    INFO    plugin/plugin.go:73    register plugin say
│ , context: ngx.timer
│ 2023/10/10 22:05:29 [warn] 17#17: *170 [lua] init.lua:953: 2023-10-10T22:05:29.677Z    WARN    server/server.go:192    conf cache ttl is 1h12m0s
│ , context: ngx.timer
│ 2023/10/10 22:05:29 [warn] 17#17: *170 [lua] init.lua:953: 2023-10-10T22:05:29.677Z    WARN    server/server.go:200    listening to /conf/apisix-1.sock
│ , context: ngx.timer
│ 2023/10/10 22:05:29 [warn] 17#17: *170 [lua] init.lua:953: 2023-10-10T22:05:29.677Z    FATAL    server/server.go:215    listen /conf/apisix-1.sock: listen unix /conf/apisix-1.sock: bind: no such file or directory     <-----
│ github.com/apache/apisix-go-plugin-runner/internal/server.Run
│     /app/internal/server/server.go:215
│ github.com/apache/apisix-go-plugin-runner/pkg/runner.Run
│     /app/pkg/runner/runner.go:52
│ main.newRunCommand.func1
│     /app/cmd/go-runner/main.go:134
│ github.com/spf13/cobra.(*Command).execute
│     /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860
│ github.com/spf13/cobra.(*Command).ExecuteC
│     /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
│ github.com/spf13/cobra.(*Command).Execute
│     /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
│ main.main
│     /app/cmd/go-runner/main.go:160
│ runtime.main
│     /usr/local/go/src/runtime/proc.go:267
│ , context: ngx.timer
│ 2023/10/10 22:05:29 [warn] 17#17: *170 [lua] init.lua:959: runner exited with reason: exit, status: 1, context: ngx.timer
│ 2023/10/10 22:05:29 [warn] 17#17: *170 [lua] init.lua:386: flush_token(): flush conf token in shared dict, context: ngx.timer
```

Versions:
```
apisix version
/opt/bitnami/apisix/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua version
3.5.0

uname -a
Linux apisix-data-plane-74d4557654-s9s4c 5.10.192-183.736.amzn2.aarch64 #1 SMP Wed Sep 6 21:15:30 UTC 2023 aarch64 GNU/Linux

ginx -V
nginx version: openresty/1.21.4.2
built with OpenSSL 1.1.1n  15 Mar 2022
TLS SNI support enabled
configure arguments: --prefix=/opt/bitnami/apisix/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.2 --add-module=../echo-nginx-module-0.63 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.33 --add-module=../ngx_lua-0.10.25 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.34 --add-module=../array-var-nginx-module-0.06 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../rds-json-nginx-module-0.16 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.13 --with-ld-opt=-Wl,-rpath,/opt/bitnami/apisix/openresty/luajit/lib --with-pcre-jit --with-http_realip_module --with-http_ssl_module --with-http_stub_status_module --with-http_v2_module --with-http_gzip_static_module --with-http_gunzip_module --with-http_auth_request_module --with-http_sub_module --with-mail_ssl_module --with-mail --with-compat --with-file-aio --with-http_addition_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module=dynamic --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_random_index_module --with-http_secure_link_module --with-http_slice_module --with-http_xslt_module=dynamic --with-ipv6 --with-md5-asm --with-sha1-asm --with-stream --with-stream_realip_module --with-stream_ssl_module --with-threads --with-stream --with-stream_ssl_preread_module

/var/go-plugins/go-runner version
2023-10-10T22:03:16.362Z	INFO	plugin/plugin.go:73	register plugin fault-injection
2023-10-10T22:03:16.362Z	INFO	plugin/plugin.go:73	register plugin limit-req
2023-10-10T22:03:16.362Z	INFO	plugin/plugin.go:73	register plugin response-rewrite
2023-10-10T22:03:16.362Z	INFO	plugin/plugin.go:73	register plugin say
version unknown-unknown-go1.21.3
```

I also did a quick test with apisix 3.6.0 by bumping the image version and same problem there:
```
/opt/bitnami/apisix/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua version
3.6.0

│ 2023/10/10 22:27:38 [warn] 15#15: *337 [lua] init.lua:979: respawning new runner..., context: ngx.timer
│ 2023/10/10 22:27:38 [warn] 15#15: *337 [lua] init.lua:961: 2023-10-10T22:27:38.814Z    INFO    plugin/plugin.go:73    register plugin fault-injection
│ , context: ngx.timer
│ 2023/10/10 22:27:38 [warn] 15#15: *337 [lua] init.lua:961: 2023-10-10T22:27:38.814Z    INFO    plugin/plugin.go:73    register plugin limit-req
│ 2023-10-10T22:27:38.814Z    INFO    plugin/plugin.go:73    register plugin response-rewrite
│ 2023-10-10T22:27:38.814Z    INFO    plugin/plugin.go:73    register plugin say
│ , context: ngx.timer
│ 2023/10/10 22:27:38 [warn] 15#15: *337 [lua] init.lua:961: 2023-10-10T22:27:38.814Z    WARN    server/server.go:192    conf cache ttl is 1h12m0s
│ , context: ngx.timer
│ 2023/10/10 22:27:38 [warn] 15#15: *337 [lua] init.lua:961: 2023-10-10T22:27:38.814Z    WARN    server/server.go:200    listening to /conf/apisix-1.sock
│ , context: ngx.timer
│ 2023/10/10 22:27:38 [warn] 15#15: *337 [lua] init.lua:961: 2023-10-10T22:27:38.814Z    FATAL    server/server.go:215    listen /conf/apisix-1.sock: list
│ github.com/apache/apisix-go-plugin-runner/internal/server.Run
│     /app/internal/server/server.go:215
│ github.com/apache/apisix-go-plugin-runner/pkg/runner.Run
│     /app/pkg/runner/runner.go:52
│ main.newRunCommand.func1
│     /app/cmd/go-runner/main.go:134
│ github.com/spf13/cobra.(*Command).execute
│     /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860
│ github.com/spf13/cobra.(*Command).ExecuteC
│     /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
│ github.com/spf13/cobra.(*Command).Execute
│     /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
│ main.main
│     /app/cmd/go-runner/main.go:160
│ runtime.main
│     /usr/local/go/src/runtime/proc.go:267
│ , context: ngx.timer
```
