### ISSUE TITLE
help request: java runner is only support epoll or kqueue

### ISSUE THREAD

**Issue by mayunSaicmotor** [apache/apisix#10719]
### Description

Dear,
I can't run my customized java plugin, please help me ,thanks!

apisix configuration as below

<img width="1701" alt="image" src="https://github.com/apache/apisix/assets/22955377/051f4f6c-0c37-4705-b3e7-aa0a2e1fcfca">

springboot start class as below
```
@SpringBootApplication(scanBasePackages = {"com.zebra", "org.apache.apisix.plugin.runner"})
@EnableDiscoveryClient

@EnableCreateCacheAnnotation
@EnableMethodCache(basePackages = "com.zebra")
@EnableScheduling
@Slf4j
public class GateWayApplication {

    public static void main(String[] args) {
        SpringApplication.run(GateWayApplication.class, args);
        
   
    }
}
```

springboot application.yml as below
<img width="1405" alt="image" src="https://github.com/apache/apisix/assets/22955377/c879e605-bae3-43c5-b2d3-be60d76a51df">

```
2023/12/27 05:35:25 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:25.533  INFO 88 --- [           main] o.a.d.rpc.protocol.dubbo.DubboProtocol   :  [DUBBO] Destroy reference: dubbo://172.18.0.67:7810/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=dubbo-plugin&bind.ip=172.18.0.67&bind.port=7810&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&group=parking-webservice-test&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&metadata-type=remote&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=88&qos.enable=false&register.ip=172.28.0.8&release=2.7.8&remote.application=parking-webservice-test&revision=2.2.5.RELEASE&side=consumer&sticky=false&timeout=5000&timestamp=1703586861374&version=1.0.0, dubbo version: 2.7.8, current host: 172.28.0.8
, context: ngx.timer
2023/12/27 05:35:25 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:25.535  INFO 88 --- [           main] org.apache.dubbo.qos.server.Server       :  [DUBBO] qos-server stopped., dubbo version: 2.7.8, current host: 172.28.0.8
, context: ngx.timer
2023/12/27 05:35:25 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:25.536  INFO 88 --- [lientWorker-1-2] o.a.d.r.t.netty4.NettyClientHandler      :  [DUBBO] The connection of /172.28.0.8:54602 -> /172.18.0.67:7809 is disconnected., dubbo version: 2.7.8, current host: 172.28.0.8
, context: ngx.timer
2023/12/27 05:35:25 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:25.541  INFO 88 --- [           main] o.a.d.config.bootstrap.DubboBootstrap    :  [DUBBO] DubboBootstrap is about to shutdown..., dubbo version: 2.7.8, current host: 172.28.0.8
, context: ngx.timer
2023/12/27 05:35:25 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:25.543  INFO 88 --- [           main] o.s.b.w.e.tomcat.GracefulShutdown        : Commencing graceful shutdown. Waiting for active requests to complete
, context: ngx.timer
2023/12/27 05:35:25 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:25.550  INFO 88 --- [tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown        : Graceful shutdown complete
, context: ngx.timer
2023/12/27 05:35:25 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:25.597  INFO 88 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
, context: ngx.timer
2023/12/27 05:35:25 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:25.602  INFO 88 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closing ...
, context: ngx.timer
2023/12/27 05:35:25 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:25.603  INFO 88 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed
, context: ngx.timer
2023/12/27 05:35:25 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:25.604  INFO 88 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
, context: ngx.timer
2023/12/27 05:35:25 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:25.604  INFO 88 --- [           main] c.a.c.n.registry.NacosServiceRegistry    : De-registering from Nacos Server now...
, context: ngx.timer
2023/12/27 05:35:25 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:25.606  INFO 88 --- [           main] c.a.c.n.registry.NacosServiceRegistry    : De-registration finished.
, context: ngx.timer
2023/12/27 05:35:34 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:34.610  WARN 88 --- [           main] o.s.b.f.support.DisposableBeanAdapter    : Destroy method 'close' on bean with name 'nacosServiceRegistry' threw an exception: java.lang.NullPointerException: Cannot invoke "com.alibaba.nacos.api.naming.NamingService.shutDown()" because "this.namingService" is null
, context: ngx.timer
2023/12/27 05:35:34 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:34.611  INFO 88 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
, context: ngx.timer
2023/12/27 05:35:34 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:34.613  INFO 88 --- [           main] c.a.c.d.s.DubboGenericServiceFactory     : The Dubbo GenericService ReferenceBeans are destroying...
, context: ngx.timer
2023/12/27 05:35:34 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:34.613  INFO 88 --- [           main] c.a.c.d.s.DubboGenericServiceFactory     : Destroyed the ReferenceBean  : <dubbo:reference /> 
, context: ngx.timer
2023/12/27 05:35:34 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:34.613  INFO 88 --- [           main] c.a.c.d.s.DubboGenericServiceFactory     : Destroyed the ReferenceBean  : <dubbo:reference /> 
, context: ngx.timer
2023/12/27 05:35:34 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:34.614  INFO 88 --- [           main] f.a.ReferenceAnnotationBeanPostProcessor : org.apache.dubbo.common.bytecode.proxy2@2582b0ef was destroying!
, context: ngx.timer
2023/12/27 05:35:34 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:34.614  INFO 88 --- [           main] f.a.ReferenceAnnotationBeanPostProcessor : org.apache.dubbo.common.bytecode.proxy2@2582b0ef was destroying!
, context: ngx.timer
2023/12/27 05:35:34 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:34.614  INFO 88 --- [           main] f.a.ReferenceAnnotationBeanPostProcessor : class org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor was destroying!
, context: ngx.timer
2023/12/27 05:35:34 [warn] 52#52: *84 [lua] init.lua:961: 2023-12-27 05:35:34.619 ERROR 88 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) ~[spring-boot-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
	at com.zebra.carcloud.openapi.apisix.plugin.dubbo.GateWayApplication.main(GateWayApplication.java:24) ~[classes!/:0.0.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[dubbo-plugin-0.0.1-SNAPSHOT-exec.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[dubbo-plugin-0.0.1-SNAPSHOT-exec.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[dubbo-plugin-0.0.1-SNAPSHOT-exec.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[dubbo-plugin-0.0.1-SNAPSHOT-exec.jar:0.0.1-SNAPSHOT]
Caused by: java.lang.RuntimeException: java runner is only support epoll or kqueue
	at org.apache.apisix.plugin.runner.server.ApplicationRunner.start(ApplicationRunner.java:111) ~[apisix-runner-core-0.4.0.jar!/:0.4.0]
	at org.apache.apisix.plugin.runner.server.ApplicationRunner.run(ApplicationRunner.java:149) ~[apisix-runner-core-0.4.0.jar!/:0.4.0]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
	... 13 common frames omitted

, context: ngx.timer
```

### Environment

- APISIX version (run `apisix version`):3.7.0
- Operating system (run `uname -a`):linux centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:  java plugin 0.4.0
- LuaRocks version, for installation issues (run `luarocks --version`):
**-JDK version  is  graalvm-jdk-17.0.9_linux-x64_bin**

**Comment by shreemaan-abhishek** [comment]
Hi, please open issues related to the java-plugin-runner here: https://github.com/apache/apisix-java-plugin-runner/. Thanks.
