### ISSUE TITLE
websocket 多层代理

### ISSUE THREAD

**Issue by xujiesh0510** [apache/apisix#4234]
### Environment

* apisix version (cmd: `apisix version`):
 
apisix websocket 一层代理  可以正常工作。

当apisix 前面 放了nginx 时候，两层代理， 请求能够打到 应用，但是几秒内就报

[2021-05-13T02:42:10.903Z] Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 ().'.

应用端报错：

2021-05-13 02:52:50.491 +00:00 [DBG] Socket opened using Sub-Protocol: 'null'.
2021-05-13 02:52:50.492 +00:00 [DBG] OnConnectedAsync started.
2021-05-13 02:52:50.496 +00:00 [DBG] Found protocol implementation for requested protocol: json.
2021-05-13 02:52:50.497 +00:00 [DBG] Completed connection handshake. Using HubProtocol 'json'.
2021-05-13 02:52:52.029 +00:00 [DBG] Socket connection closed prematurely.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsServerTransport.StartReceiving(WebSocket socket)
2021-05-13 02:52:52.029 +00:00 [DBG] Waiting for the application to finish sending data.
2021-05-13 02:52:52.029 +00:00 [DBG] OnConnectedAsync ending.
2021-05-13 02:52:52.030 +00:00 [DBG] Socket closed.
2021-05-13 02:52:52.030 +00:00 [DBG] Removing connection HbEZKilbipdqzP54pIMSag from the list of connections.

怎么解决呢？

**Comment by spacewander** [comment]
> apisix websocket 一层代理 可以正常工作。
> 当apisix 前面 放了nginx 时候，两层代理， 请求能够打到 应用，但是几秒内就报

We don't solve the problem caused by Nginx.
And we can't help you if you don't even fill the Environment info.

**Comment by xujiesh0510** [comment]
ok， if you are sure it's not apisix 's  problem . i will close this issue

**Comment by ChinaSilence** [comment]
same issue

**Comment by ChinaSilence** [comment]
Please open this issue, because there is no problem in spring cloud gateway with same nginx config. 

Maybe it's Apisix's bug .

**Comment by xujiesh0510** [comment]
我这没有权限重新打开 issue呢，@ChinaSilence 你重新建一个issue吧。 我目前是没采用 帖子里面的 两层代理
