### ISSUE TITLE
Request help: dubbo proxy occur some error about dubbo version

### ISSUE THREAD

**Issue by liangliang4ward** [apache/apisix#6354]
### Issue description

I try demo be based on  [https://apisix.apache.org/zh/docs/apisix/plugins/dubbo-proxy](url);

but dubbo return error like 

```java
17:26:43.281 [DubboServerHandler-172.29.43.235:20880-thread-2] WARN org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation -  [DUBBO] Decode rpc invocation failed: Service org.apache.dubbo.sample.tengine.DemoService with version 0.0.0 not found, invocation rejected., dubbo version: 3.0.5, current host: 172.29.43.235
java.io.IOException: Service org.apache.dubbo.sample.tengine.DemoService with version 0.0.0 not found, invocation rejected.
        at org.apache.dubbo.remoting.transport.CodecSupport.checkSerialization(CodecSupport.java:166)
        at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:138)
        at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:93)
        at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
        at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:44)
        at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
        at java.lang.Thread.run(Thread.java:750)
```

my config like this:
```json
curl http://127.0.0.1:9180/apisix/admin/routes/1  -H 'X-API-KEY: xxxx' -X PUT -d '
{
    "uris": [
        "/hello"
    ],
    "plugins": {
        "dubbo-proxy": {
            "service_name": "org.apache.dubbo.sample.tengine.DemoService",
            "service_version": "3.0.5",
            "method": "tengineDubbo"
        }
    },
    "upstream_id": 1
}'
```

### Environment

- apisix version (cmd: `apisix version`): 2.12.1
- OS (cmd: `uname -a`): Linux DESKTOP-QE043PO 5.4.72-microsoft-standard-WSL2  MP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by liangliang4ward** [comment]
It's my mistake.
`org.apache.dubbo.sample.tengine.DemoService` need to `org.apache.dubbo.samples.tengine.DemoService`
